# Generated by Django 2.2.14 on 2021-03-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=25)),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HomeImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='assests/upload')),
                ('img2', models.ImageField(upload_to='assests/upload')),
                ('img3', models.ImageField(upload_to='assests/upload')),
                ('img4', models.ImageField(upload_to='assests/upload')),
                ('img5', models.ImageField(upload_to='assests/upload')),
                ('img6', models.ImageField(upload_to='assests/upload')),
                ('img7', models.ImageField(upload_to='assests/upload')),
                ('img8', models.ImageField(upload_to='assests/upload')),
            ],
        ),
    ]
