# Generated by Django 2.2.14 on 2021-03-07 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeimages',
            old_name='img1',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='homeimages',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='homeimages',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='homeimages',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='homeimages',
            name='img5',
        ),
        migrations.RemoveField(
            model_name='homeimages',
            name='img6',
        ),
        migrations.RemoveField(
            model_name='homeimages',
            name='img7',
        ),
        migrations.RemoveField(
            model_name='homeimages',
            name='img8',
        ),
    ]
